"""initial schema

Revision ID: dd149a38612f
Revises: 
Create Date: 2026-05-06 12:48:10.015767

"""

# flake8: noqa

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'dd149a38612f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('suspended_until', sa.Integer(), nullable=True),
    sa.Column('last_authenticated_at', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=16), server_default=sa.text("'reader'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('failed_password_attempts', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('password_verified_at', sa.Integer(), nullable=True),
    sa.Column('mfa_session_uuid', sa.String(length=80), nullable=True),
    sa.Column('totp_secret_encrypted', sa.String(length=255), nullable=False),
    sa.Column('failed_totp_attempts', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('recovery_code_hash', sa.String(length=255), nullable=False),
    sa.Column('failed_recovery_code_attempts', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('current_jti_encrypted', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.String(length=4096), nullable=True),
    sa.CheckConstraint("role IN ('reader', 'writer', 'editor', 'admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mfa_session_uuid'),
    sa.UniqueConstraint('username'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_display_name'), ['display_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(length=128), nullable=False),
    sa.Column('request_uuid', sa.String(length=64), nullable=True),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_request_uuid'), ['request_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_resource_type'), ['resource_type'], unique=False)

    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('dirname', sa.String(length=255), nullable=False),
    sa.Column('is_write_protected', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('summary', sa.String(length=4096), nullable=True),
    sa.Column('children_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('files_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('files_count >= 0', name='ck_folders_files_count_non_negative'),
    sa.CheckConstraint('children_count >= 0', name='ck_folders_children_count_non_negative'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_folders_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_folders_dirname'), ['dirname'], unique=False)
        batch_op.create_index(batch_op.f('ix_folders_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_folders_updated_by'), ['updated_by'], unique=False)

    op.create_index(
        "uq_folders_parent_id_dirname",
        "folders",
        [sa.text("coalesce(parent_id, -1)"), "dirname"],
        unique=True,
    )

    op.create_table('variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('variable_key', sa.String(length=255), nullable=False),
    sa.Column('variable_value', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('variables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_variables_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_variables_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_variables_namespace'), ['namespace'], unique=False)
        batch_op.create_index(batch_op.f('ix_variables_updated_by'), ['updated_by'], unique=False)
        batch_op.create_index('uq_variables_namespace_variable_key', ['namespace', 'variable_key'], unique=True)

    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('is_starred', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filesize', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('mimetype', sa.String(length=255), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.String(length=4096), nullable=True),
    sa.Column('comments_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('latest_revision_number', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('comments_count >= 0', name='ck_files_comments_count_non_negative'),
    sa.CheckConstraint('filesize >= 0', name='ck_files_filesize_non_negative'),
    sa.CheckConstraint('latest_revision_number >= 0', name='ck_files_latest_revision_number_non_negative'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_id', 'filename', name='uq_file_folder_filename'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_filename'), ['filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_filesize'), ['filesize'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_folder_id'), ['folder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_is_starred'), ['is_starred'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_mimetype'), ['mimetype'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_updated_by'), ['updated_by'], unique=False)

    op.create_table('files_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=4096), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('files_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_comments_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_comments_file_id'), ['file_id'], unique=False)

    op.create_table('files_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('revision_number', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('revision_uuid', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filesize', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('mimetype', sa.String(length=255), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.CheckConstraint('filesize >= 0', name='ck_files_revisions_filesize_non_negative'),
    sa.CheckConstraint('revision_number >= 1', name='ck_files_revisions_revision_number_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_uuid'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('files_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_revisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_revisions_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_revisions_file_id'), ['file_id'], unique=False)
        batch_op.create_index('uq_files_revisions_file_id_revision_number', ['file_id', 'revision_number'], unique=True)

    op.create_table('files_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('files_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_tags_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_tags_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_tags_file_id'), ['file_id'], unique=False)

    op.create_index(
        "uq_files_tags_file_id_tag",
        "files_tags",
        ["file_id", sa.text("lower(tag)")],
        unique=True,
    )

    op.create_table('files_thumbnails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('thumbnail_uuid', sa.String(length=255), nullable=False),
    sa.Column('filesize', sa.Integer(), nullable=False),
    sa.Column('mimetype', sa.String(length=255), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.CheckConstraint('filesize > 0', name='ck_files_thumbnails_filesize_positive'),
    sa.CheckConstraint('height > 0', name='ck_files_thumbnails_height_positive'),
    sa.CheckConstraint('width > 0', name='ck_files_thumbnails_width_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thumbnail_uuid'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('files_thumbnails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_thumbnails_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_thumbnails_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_thumbnails_file_id'), ['file_id'], unique=False)
        batch_op.create_index('uq_files_thumbnails_file_id', ['file_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files_thumbnails', schema=None) as batch_op:
        batch_op.drop_index('uq_files_thumbnails_file_id')
        batch_op.drop_index(batch_op.f('ix_files_thumbnails_file_id'))
        batch_op.drop_index(batch_op.f('ix_files_thumbnails_created_by'))
        batch_op.drop_index(batch_op.f('ix_files_thumbnails_created_at'))

    op.drop_table('files_thumbnails')
    with op.batch_alter_table('files_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_tags_file_id'))
        batch_op.drop_index(batch_op.f('ix_files_tags_created_by'))
        batch_op.drop_index(batch_op.f('ix_files_tags_created_at'))

    op.drop_index("uq_files_tags_file_id_tag", table_name="files_tags")
    op.drop_table('files_tags')
    with op.batch_alter_table('files_revisions', schema=None) as batch_op:
        batch_op.drop_index('uq_files_revisions_file_id_revision_number')
        batch_op.drop_index(batch_op.f('ix_files_revisions_file_id'))
        batch_op.drop_index(batch_op.f('ix_files_revisions_created_by'))
        batch_op.drop_index(batch_op.f('ix_files_revisions_created_at'))

    op.drop_table('files_revisions')
    with op.batch_alter_table('files_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_comments_file_id'))
        batch_op.drop_index(batch_op.f('ix_files_comments_created_by'))
        batch_op.drop_index(batch_op.f('ix_files_comments_created_at'))

    op.drop_table('files_comments')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_updated_by'))
        batch_op.drop_index(batch_op.f('ix_files_mimetype'))
        batch_op.drop_index(batch_op.f('ix_files_is_starred'))
        batch_op.drop_index(batch_op.f('ix_files_folder_id'))
        batch_op.drop_index(batch_op.f('ix_files_filesize'))
        batch_op.drop_index(batch_op.f('ix_files_filename'))
        batch_op.drop_index(batch_op.f('ix_files_created_by'))
        batch_op.drop_index(batch_op.f('ix_files_created_at'))

    op.drop_table('files')
    with op.batch_alter_table('variables', schema=None) as batch_op:
        batch_op.drop_index('uq_variables_namespace_variable_key')
        batch_op.drop_index(batch_op.f('ix_variables_updated_by'))
        batch_op.drop_index(batch_op.f('ix_variables_namespace'))
        batch_op.drop_index(batch_op.f('ix_variables_created_by'))
        batch_op.drop_index(batch_op.f('ix_variables_created_at'))

    op.drop_table('variables')
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_folders_updated_by'))
        batch_op.drop_index(batch_op.f('ix_folders_parent_id'))
        batch_op.drop_index(batch_op.f('ix_folders_dirname'))
        batch_op.drop_index(batch_op.f('ix_folders_created_by'))

    op.drop_index("uq_folders_parent_id_dirname", table_name="folders")
    op.drop_table('folders')
    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_request_uuid'))
        batch_op.drop_index(batch_op.f('ix_audit_event'))
        batch_op.drop_index(batch_op.f('ix_audit_created_by'))
        batch_op.drop_index(batch_op.f('ix_audit_created_at'))

    op.drop_table('audit')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_display_name'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    # ### end Alembic commands ###
